[package]
name = "sc-cli-derive"
version = "0.8.0-alpha.2"
authors = ["Cecile Tonglet <cecile@parity.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", default-features = false, features = ["derive", "parsing", "proc-macro"] }
quote = "1"
proc-macro2 = "1"
heck = "0.3.0"
proc-macro-error = "0.4.7"
platforms = "0.2"

[dev-dependencies]
trybuild = "1.0"
sc-service = { version = "0.8.0-alpha.2", default-features = false, path = "../service" }
sc-cli = { version = "0.8.0-alpha.2", default-features = false, path = "../cli" }
sp-runtime = { version = "2.0.0-alpha.2", default-features = false, path = "../../primitives/runtime" }
sp-storage = { version = "2.0.0-alpha.2", default-features = false, path = "../../primitives/storage" }
serde = { version = "1.0.101", features = ["derive"] }
