[package]
name = "cli-utils"
version = "2.0.0-alpha.3"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "CLI utils"
documentation = "https://docs.rs/cli-utils"

[dependencies]
frame-system = { version = "2.0.0-alpha.4", default-features = false, path = "../../frame/system" }
pallet-balances = { version = "2.0.0-alpha.4", default-features = false, path = "../../frame/balances" }
sp-runtime = { version = "2.0.0-alpha.4", default-features = false, path = "../../primitives/runtime" }

[features]
default = ["std"]
std = [
    "frame-system/std",
    "pallet-balances/std",
    "sp-runtime/std",
]
