[package]
name = "sc-cli"
version = "0.8.0-alpha.4"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate CLI interface."
edition = "2018"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[dependencies]
clap = "2.33.0"
derive_more = "0.99.2"
env_logger = "0.7.0"
log = "0.4.8"
atty = "0.2.13"
regex = "1.3.1"
time = "0.1.42"
ansi_term = "0.12.1"
lazy_static = "1.4.0"
app_dirs = "1.2.1"
tokio = { version = "0.2.9", features = [ "signal", "rt-core", "rt-threaded" ] }
futures = "0.3.1"
fdlimit = "0.1.4"
serde_json = "1.0.41"
parity-scale-codec = "1.2.0"
hex = "0.4.2"
hyper = "0.12.35"
rand = "0.7.2"
serde = "1.0.104"
futures01 = { package = "futures", version = "0.1.29" }
sc-rpc = { version = "2.0.0-alpha.3", path = "../../client/rpc" }
jsonrpc-core-client = { version = "14.0.3", features = ["http"] }
tiny-bip39 = "0.6.2"
libp2p = "0.15.0"
hex-literal = "0.2.1"
sc-informant = { version = "0.8.0-alpha.4", path = "../informant" }
sp-panic-handler = { version = "2.0.0-alpha.4", path = "../../primitives/panic-handler" }
sc-client-api = { version = "2.0.0-alpha.4", path = "../api" }
sp-blockchain = { version = "2.0.0-alpha.4", path = "../../primitives/blockchain" }
sc-network = { version = "0.8.0-alpha.4", path = "../network" }
sp-runtime = { version = "2.0.0-alpha.4", path = "../../primitives/runtime" }
sp-version = { version = "2.0.0-alpha.3", path = "../../primitives/version" }
sp-io = { version = "2.0.0-alpha.3", path = "../../primitives/io" }
sp-core = { version = "2.0.0-alpha.4", path = "../../primitives/core" }
sc-service = { version = "0.8.0-alpha.4", default-features = false, path = "../service" }
sp-state-machine = { version = "0.8.0-alpha.4", path = "../../primitives/state-machine" }
sc-telemetry = { version = "2.0.0-alpha.4", path = "../telemetry" }
substrate-prometheus-endpoint = { path = "../../utils/prometheus" , version = "0.8.0-alpha.4"}
sp-keyring = { version = "2.0.0-alpha.4", path = "../../primitives/keyring" }
names = "0.11.0"
structopt = "0.3.8"
sc-tracing = { version = "2.0.0-alpha.4", path = "../tracing" }
chrono = "0.4.10"
parity-util-mem = { version = "0.6.0", default-features = false, features = ["primitive-types"] }
cli-utils = { path = "../../utils/cli-utils" , version = "2.0.0-alpha.3" }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
rpassword = "4.0.1"

[dev-dependencies]
tempfile = "3.1.0"
substrate-test-runtime = { version = "2.0.0-dev", features = ["indices-lookup"], path = "../../test-utils/runtime" }
sp-application-crypto = { version = "2.0.0-alpha.2", default-features = false, path = "../../primitives/application-crypto" }
frame-system = { version = "2.0.0-aplha.4", path = "../../frame/system" }

[features]
wasmtime = [
	"sc-service/wasmtime",
]
