[package]
name = "sc-cli-derive"
version = "0.8.0-alpha.5"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Procedureal macros for Substrate CLI interface"
edition = "2018"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", default-features = false, features = ["parsing", "proc-macro"] }
quote = "1"
proc-macro2 = "1"
proc-macro-error = "0.4.7"
platforms = "0.2"

[dev-dependencies]
sc-service = { version = "0.8.0-alpha.5", default-features = false, path = "../../service" }
sc-cli = { version = "0.8.0-alpha.5", default-features = false, path = ".." }
