[package]
name = "pallet-balances-cli"
version = "2.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sp-core = { version = "2.0.0-dev", path = "../../../primitives/core" }
sc-cli = { version = "0.8.0-dev", path = "../../../client/cli" }
sp-runtime = { version = "2.0.0-dev", path = "../../../primitives/runtime" }
structopt = "0.3.8"
codec = { version = "1.3.0", package = "parity-scale-codec" }
cli-utils = { path = "../../cli-utils", version = "2.0.0-dev" }
hex = "0.4.2"

[dev-dependencies]
sp-io = { version = "2.0.0-dev", path = "../../../primitives/io" }
frame-system = { version = "2.0.0-alpha.4", path = "../../../frame/system" }
substrate-test-runtime = { version = "2.0.0-dev", features = ["indices-lookup"], path = "../../../test-utils/runtime" }
